### ISSUE TITLE
Spezifische Attribute

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sjas#2]
Zusätzliche Attribute auf der Person

- [x] Mehrere Sprachen auf der Person inkl. Kenntnisstand. Siehe Issue #13
- [x] Heimatort -> Textfeld auf der Person
- [x] Kontaktperson -> Auf dem Event/Lager via Anmeldeangaben
