### ISSUE TITLE
Lager-Modul

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sjas#3]
Anpassen am Events/Lagermodul
• Anpassungen der Anmeldebestätigung
• «Häckchen» setzen für das Gesuchsformular Reduktion: Ja/Nein und dann einen Link zum Formular

-> Durchklicken eines Events in der Testumgebung und Anpassungen festhalten. Am Beispiel https://puzzle.hitobito.com/de/groups/1/events/15

Anpassungen:

- [x] Neues Tab  "Lager" basierend auf "Events". #14 
- [x] Neue Art von Application Questions als Boolen. Mit einer Checkbox #15
- [x] Anpassen von Bemerkungsfeld https://github.com/hitobito/hitobito/issues/946
- [x] Bestätigungsmail an Teilnehmer #22
