### ISSUE TITLE
PEOPLE: Neue Felder auf Personen

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_sjas#90]
Die SJAS hätte gerne drei neue Freitextfelder. 
Diese sollen im Personenexport "Alle Angaben" auch enthalten sein.

---

Bei der Hitobito-Umgebung der Jubla gibt es die drei Freitextfelder "Bankverbindung", "Versicherung" und "Versicherungsnummer". 
Diese sollen genau gleich auch in den SJAS-Wagon übernommen werden.
Analog dem Jubla-Wagon, sollen die drei Felder auch im Export "Alle Angaben" enthalten sein.
Änderungen an den Feldern sollen korrekt im Personen-Log erscheinen.

Ansonnsten haben die Felder keinerlei Logik und sind auch nicht an spezielle Berechtigungen gebunden.
Wer die Person sehen kann, sieht auch die Felder. Wer Schreibrechte auf die Person hat, kann auch diese Felder bearbeiten.

# Mockup

![grafik](https://github.com/user-attachments/assets/3649e7e3-57a1-4193-a66d-f382e4c9288b)

# ToDo

- [x] Migration erstellen, um die neuen Spalten hinzuzufügen
- [x] Model anpassen: SEARCHABLE_ATTRS erweitern
- [x] Views anpassen: `people/details` und `people/fields` wie bei der Jubla erweitern
- [x] Specs schreiben, die das vorhandensein und die Suchbarkeit prüfen
- [ ] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
